### ISSUE TITLE
support for CC

### ISSUE THREAD

**Issue by bexelbie** [mesozoic/gmail-yaml-filters#16]
Can we add a test for CC similarly to TO?

**Comment by mesozoic** [comment]
`cc:` doesn't exist in [Gmail's Filter resource](https://developers.google.com/gmail/api/v1/reference/users/settings/filters#resource), so the way to do this today is with `has: "cc:whatever"`. However, I'll leave this issue open for a bit, because it should be easy enough to add support for [Gmail's custom search operators](https://support.google.com/mail/answer/7190?hl=en) to declutter your configuration file.
