### ISSUE TITLE
Supported actions Categorize

### ISSUE THREAD

**Issue by kcampion** [mesozoic/gmail-yaml-filters#19]
Is it possible to add some new supported actions for `Categorize`?

![Capture d’écran 2020-02-15 à 11 03 49](https://user-images.githubusercontent.com/507265/74586033-98ec1280-4fe3-11ea-998d-bf474c804cc3.png)

The export from Gmail generates this:
```
# for Primary
<apps:property name='smartLabelToApply' value='^smartlabel_personal'/>
# for Social
<apps:property name='smartLabelToApply' value='^smartlabel_social'/>
# for Updates
<apps:property name='smartLabelToApply' value='^smartlabel_notification'/>
# for Forums
<apps:property name='smartLabelToApply' value='^smartlabel_group'/>
# for Promotions
<apps:property name='smartLabelToApply' value='^smartlabel_promo'/>
```

**Comment by mesozoic** [comment]
Interesting, I haven't seen that property before. But I've been using `label: CATEGORY_PERSONAL` to do the same thing (see [Gmail > API > Managing Labels](https://developers.google.com/gmail/api/guides/labels)). Can you give that a try?

We could add support for `categorize: personal` with a bit of validation, but since it's syntactic sugar for something you can already do, I'd be happy to take pull requests 😄

**Comment by kcampion** [comment]
Great, `label: CATEGORY_PERSONAL` and others work well indeed :)

Is it possible to add this possibility in the documentation?

```
* `label`
  * (to display in the Categorize tab of the Gmail interface, you can use CATEGORY_PERSONAL, CATEGORY_SOCIAL, CATEGORY_PROMOTIONS, CATEGORY_UPDATES or CATEGORY_FORUMS)
```

**Comment by mesozoic** [comment]
I’m not at a keyboard today but I’ll accept PRs :)

**Comment by kcampion** [comment]
https://github.com/mesozoic/gmail-yaml-filters/pull/21
