### ISSUE TITLE
Applying labels to messages and threads

### ISSUE THREAD

**Issue by kcampion** [mesozoic/gmail-yaml-filters#20]
When we  upload or sync a configuration, the filters are created but not applied to all old emails.

Is it possible to apply the filters to all conversations?

![Capture d’écran 2020-02-15 à 12 14 37](https://user-images.githubusercontent.com/507265/74586916-f33da100-4fec-11ea-927d-7696d4db5055.png)

I read this but I'm not sure that is to do what I explain: https://developers.google.com/gmail/api/guides/labels#applying_labels_to_messages_and_threads

**Comment by mesozoic** [comment]
Yeah, this would be a great feature; I’ve found myself wishing for this a few times. 

As far as I can tell, there’s no way to do this as part of creating a label in the Gmail API. I think we’d have to execute the search, iterate through each message, then interpret  and apply each rule using the rest of the APIs. I think that’s a pretty substantial expansion of scope (modifying your emails, rather than just modifying your filters) and I don’t plan on adding it to this tool. 

As always, I am open to pull requests if someone else wants to take this on. But I’m going to close this for now because I don’t intend to add it myself.
